// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi36NOg3sVagOWMKsBTpPNsRfBk71hCpo',
    appId: '1:581756819357:web:2fef072b2c4ae50afec174',
    messagingSenderId: '581756819357',
    projectId: 'ernu-project',
    authDomain: 'ernu-project.firebaseapp.com',
    storageBucket: 'ernu-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBYAgLkIiHZkODNnWgCZc9r6sDfRiEA3s',
    appId: '1:581756819357:android:880cddfb58fdb22bfec174',
    messagingSenderId: '581756819357',
    projectId: 'ernu-project',
    storageBucket: 'ernu-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7sTjf4u6Ecdu-K6Ig75F7PTyFqa8pJfk',
    appId: '1:581756819357:ios:2f8e0b2870a60be2fec174',
    messagingSenderId: '581756819357',
    projectId: 'ernu-project',
    storageBucket: 'ernu-project.appspot.com',
    iosBundleId: 'com.titi.ernu',
  );
}
